export const BUSINESS_RULES = {
  WALLET: {
    INITIAL_BALANCE: 0,
    MINIMUM_RECHARGE: 100,
    LOW_BALANCE_THRESHOLD: 50,
    INSUFFICIENT_THRESHOLD_MULTIPLIER: 5, // pricePerMin * 5 to connect
  },
  CONSULTATION: {
    DEFAULT_RATE_PER_MIN: 25,
    GRACE_PERIOD_SECONDS: 30,
    TICK_INTERVAL_MS: 1000,
    SPEED_UP_TICK_INTERVAL_MS: 1000, // keep ticks regular, change minutes conversion
    SPEED_UP_SECONDS_PER_MINUTE: 10,
    STANDARD_SECONDS_PER_MINUTE: 60,
    // Safe fallback boundaries if server response is missing or malformed
    HEARTBEAT_INTERVAL_SECONDS_FALLBACK: 30,
    HEARTBEAT_INTERVAL_MIN: 10,
    HEARTBEAT_INTERVAL_MAX: 60,
  },
  STORAGE_VERSION: 2,
};
